[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_WEBSOCKET_URL = "wss://canvas-flow-backend.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200